- name: Status mysql
  shell: >- 
    systemctl status {{ mysql_run_service }}.service 2>&1 || echo ' -> Please pay attention to viewing the logs.'
  register: mysql_status

- name: Show mysql status
  debug: msg="{{ mysql_status.stdout_lines }}"