- include_tasks:
    file: actions/install.yml
    apply:
      tags:
        - install
  tags:
    - install

- include_tasks:
    file: actions/config.yml
    apply:
      tags:
        - config
  tags:
    - config

- include_tasks:
    file: actions/enable.yml
    apply:
      tags:
        - enable
  tags:
    - enable

- include_tasks:
    file: actions/start.yml
    apply:
      tags:
        - start
  tags:
    - start

- include_tasks:
    file: actions/restart.yml
    apply:
      tags:
        - restart
  tags:
    - restart

- include_tasks:
    file: actions/status.yml
    apply:
      tags:
        - status
  tags:
    - status

- include_tasks:
    file: actions/stop.yml
    apply:
      tags:
        - stop
  tags:
    - stop

- include_tasks:
    file: actions/uninstall.yml
    apply:
      tags:
        - uninstall
  tags:
    - uninstall
