- name: Status ketadb
  shell: >-
    systemctl status {{ ketadb_run_service }}.service 2>&1 || echo ' -> Please pay attention to viewing the logs.'
  register: ketadb_status
  ignore_errors: true

- name: Show ketadb status
  debug: msg="{{ ketadb_status.stdout_lines }}"
